### ISSUE TITLE
Consider splitting into two crates

### ISSUE THREAD

**Issue by shepmaster** [tupshin/cassandra-rs#11]
Ideally, crates that provide C-to-Rust bindings [have the suffix `-sys`](http://doc.crates.io/build-script.html#-sys-packages), but that doesn't appear to be the case here. This allows multiple nice user-facing interfaces to be built on top of shared code, and avoids an issue where you try to link to the same native library multiple times.

**Comment by tupshin** [comment]
The actual linking to C happens in [cql_bindgen](https://github.com/tupshin/cql-bindgen/blob/master/src/cassandra.rs) which has its own [published crate](https://github.com/tupshin/cql-bindgen/blob/master/src/cassandra.rs). While that crate probably should be "-sys" renamed, the split you describe already exists. I do intent this crate to remain fairly low level, however, and to provide as its goals only safety and a somewhat rustic api. I'm hoping that there would be very little need to have other projects building directly on the bindgen one, and instead can build higher abstratction layers on top of this one due to minimal overhead and it not being particularly opinionated.

**Comment by shepmaster** [comment]
> The actual linking to C happens in cql_bindgen which has its own published crate

:+1: Sounds like I just misread the code. I'll close this to admit my error! :innocent:
